const miles = 30;
const kilometers = 70;
const number = 1.609344;
const kilometersToMiles = kilometers / number;
const milesToKilometers = miles * number;
const kilometersAre = kilometers + " kilometers are:";
const kilometersMiles = kilometersToMiles + " miles";
const milesAre = miles + " miles are:";
const milesKilometers = milesToKilometers + " kilometers";
console.log("Distance conversions");
console.log("-------------------------");
console.log(kilometersAre);
console.log(kilometersMiles);
console.log("----");
console.log(milesAre);
console.log(milesKilometers);
console.log("\n");
const celsius = 10;
const fahrenheit = 50;
const celsiusToFahrenheit = (celsius * 9 / 5) + 32;
const fahrenheitToCelsius = (fahrenheit - 32) * 5 / 9;
const fahrenheitAre = fahrenheit + " degrees Fahrenheit are:";
const fahrenheitCelsius = fahrenheitToCelsius + " degrees Celsius";
const celsiusAre = celsius + " degrees Celsius are:";
const celsiusFahrenheit = celsiusToFahrenheit + " degrees Fahrenheit";
console.log("Temperature conversions");
console.log("---------------------------");
console.log(fahrenheitAre);
console.log(fahrenheitCelsius);
console.log("----");
console.log(celsiusAre);
console.log(celsiusFahrenheit);
console.log("\n");
const grams = 100;
const kilograms = 28;
const gramsToKilograms = grams / 1000;
const kilogramsToGrams = kilograms * 1000;
const kilogramsAre = kilograms + " Kilograms are:";
const kilogramsGrams = kilogramsToGrams + " Grams";
const gramsAre = grams + " Grams are:";
const gramsKilograms = gramsToKilograms + " Kilograms";
console.log("Kilograms conversions");
console.log("-------------------------");
console.log(kilogramsAre);
console.log(kilogramsGrams);
console.log("----");
console.log(gramsAre);
console.log(gramsKilograms);

const listItemArray = document.querySelectorAll("li");
listItemArray[0].innerHTML = "Distance conversions:";
listItemArray[5].innerHTML = "Temperature conversions:";
listItemArray[10].innerHTML = "Kilograms conversions:";

listItemArray[1].innerHTML = kilometersAre;
listItemArray[2].innerHTML = kilometersMiles;
listItemArray[3].innerHTML = milesAre;
listItemArray[4].innerHTML = milesKilometers;

listItemArray[6].innerHTML = fahrenheitAre;
listItemArray[7].innerHTML = fahrenheitCelsius;
listItemArray[8].innerHTML = celsiusAre;
listItemArray[9].innerHTML = celsiusFahrenheit;

listItemArray[11].innerHTML = kilogramsAre;
listItemArray[12].innerHTML = kilogramsGrams;
listItemArray[13].innerHTML = gramsAre;
listItemArray[14].innerHTML = gramsKilograms;